name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --no-default-features --verbose
    - name: Run tests
      run: cargo test --no-default-features --verbose
